# Generated by Django 5.2.8 on 2025-11-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20220911_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermetainfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
